name: AxFastTravel
main: me.DMan16.AxFastTravel.AxFastTravel
depend: [AxUtils,AxEconomy]
softdepend: [WorldGuard,AxItems]
version: 1.0
description: FastTravel for Aldreda
author: DMan16
api-version: 1.16

commands:
  AxFastTravel:
    permission: aldreda.command.fasttravel
permissions:
  aldreda.command.fasttravel:
    default: op